import type { Dispatch, SetStateAction } from 'react';
import type { Edge, Node } from '@xyflow/react';
import type { BridgeCallOptions, BridgeToast } from './electronBridgeTypes';
import { type FlowTemplate } from '../lib/flowTemplates';
import type { ArtifactContent, ArtifactSnapshot, BridgeResult, FlowSnapshot, FlowVersionSnapshot, GeneratedScriptResult, PickerOpenPayload, PickerRequest, QueueStats, RpaBridge, BrowserExecutorKind, RunFailureStrategy, RunMode, RunScope, ScheduleRunSummary, ScheduleSnapshot, SiteAnalysisResult, TaskSnapshot } from '../types/electron';
import type { FlowCanvasSnapshot, RpaNodeData, RunLogEntry, RuntimeStatus, RuntimeVariable } from '../types/rpa';

export type UseElectronBridgeActionsParams = {
  activeFlowNameRef: import('react').MutableRefObject<string>;
  activeRunId: string | null;
  activeRunFlowId: string | null;
  callBridge: <T>(action: (bridge: RpaBridge) => Promise<BridgeResult<T>>, successMessage?: string, options?: BridgeCallOptions) => Promise<T | null>;
  clearLastRunOverrides: () => void;
  currentFlow: FlowSnapshot | null;
  flowCanvas: FlowCanvasSnapshot;
  flows: FlowSnapshot[];
  pushToast: (type: BridgeToast['type'], message: string, icon?: string) => number;
  dismissToast: (toastId: number) => void;
  inputVariables: RuntimeVariable[];
  runtimeVariables: RuntimeVariable[];
  resetRunView: () => void;
  restoreRecentRun: (flowId: string) => Promise<void>;
  setLastRunOverrides: (flowKey: string | null, variables: RuntimeVariable[]) => void;
  setCurrentFlow: Dispatch<SetStateAction<FlowSnapshot | null>>;
  setFlowEdges: Dispatch<SetStateAction<Edge[]>>;
  setFlowNodes: Dispatch<SetStateAction<Node<RpaNodeData>[]>>;
  setFlows: Dispatch<SetStateAction<FlowSnapshot[]>>;
  setInputVariables: (variables: RuntimeVariable[]) => void;
  setSelectedNodeId?: Dispatch<SetStateAction<string>>;
  setActiveRunId: Dispatch<SetStateAction<string | null>>;
  setActiveRunFlowId: Dispatch<SetStateAction<string | null>>;
  setArtifactContent: Dispatch<SetStateAction<ArtifactContent | null>>;
  setArtifacts: Dispatch<SetStateAction<ArtifactSnapshot[]>>;
  setGeneratedScript: Dispatch<SetStateAction<GeneratedScriptResult | null>>;
  setQueueStats: Dispatch<SetStateAction<QueueStats | null>>;
  setRuntimeStatus: Dispatch<SetStateAction<RuntimeStatus>>;
  setRuns: Dispatch<SetStateAction<TaskSnapshot[]>>;
  setSchedules: Dispatch<SetStateAction<ScheduleSnapshot[]>>;
  setScheduleRunSummaries: Dispatch<SetStateAction<Record<string, ScheduleRunSummary>>>;
  setSiteAnalysis: Dispatch<SetStateAction<SiteAnalysisResult | null>>;
  setVariables: Dispatch<SetStateAction<RuntimeVariable[]>>;
  setLogs: Dispatch<SetStateAction<RunLogEntry[]>>;
  setConfirmationMessage: Dispatch<SetStateAction<string | null>>;
  setActivePickerRequest: Dispatch<SetStateAction<PickerRequest | null>>;
  setCanvasFitVersion: Dispatch<SetStateAction<number>>;
};

export type ElectronBridgeActions = {
  openArtifactPath: (storageUrl: string) => Promise<void>;
  openFlow: () => Promise<boolean>;
  applyFlowTemplate: (template: FlowTemplate) => void;
  openFlowById: (flowId: string) => Promise<void>;
  /** 静默恢复 currentFlow；restoreCanvas: true 时同时应用到画布（启动时无草稿场景使用） */
  silentlyRestoreCurrentFlow: (flowId: string, options?: { restoreCanvas?: boolean }) => Promise<void>;
  /** AI 更新流程后的轻量画布刷新：不清运行日志/草稿，不弹 toast */
  applyAiFlowUpdate: (flowId: string) => Promise<void>;
  loadFlowVersions: () => Promise<FlowVersionSnapshot[]>;
  rollbackFlowSnapshot: (snapshot: FlowVersionSnapshot) => Promise<boolean>;
  saveFlow: () => Promise<void>;
  exportFlow: () => Promise<void>;
  exportFlowById: (flowId: string) => Promise<void>;
  createNewFlow: (name?: string) => Promise<boolean>;
  loadFlows: (options?: BridgeCallOptions) => Promise<void>;
  archiveCurrentFlow: () => Promise<void>;
  archiveFlowById: (flowId: string) => Promise<void>;
  duplicateFlowById: (flowId: string) => Promise<void>;
  moveFlowById: (flowId: string, folderPath: string) => Promise<void>;
  setFlowStatusById: (flowId: string, status: import('../types/electron').FlowStatus) => Promise<void>;
  deleteCurrentFlow: () => Promise<void>;
  deleteFlowById: (flowId: string) => Promise<void>;
  renameCurrentFlow: (name: string) => Promise<void>;
  setDefaultBrowserExecutor: (browserExecutor: BrowserExecutorKind) => Promise<void>;
  exportLogs: (content: string) => Promise<void>;
  openPicker: (payload: PickerOpenPayload) => Promise<void>;
  closePicker: (requestId: string) => Promise<void>;
  startRun: (options?: RunMode | StartRunOptions) => Promise<void>;
  stopRun: () => Promise<void>;
  resumeConfirmation: () => Promise<void>;
  generateScraplingScript: () => Promise<void>;
  exportScraplingScript: (content: string, filename: string) => Promise<void>;
  analyzeCurrentSite: () => Promise<void>;
  loadRuns: (options?: { flowId?: string; limit?: number } & BridgeCallOptions) => Promise<void>;
  loadFlowRuns: (flowId: string, options?: { limit?: number } & BridgeCallOptions) => Promise<void>;
  loadTaskVariables: (taskId: string) => Promise<void>;
  loadArtifacts: (taskId: string) => Promise<void>;
  readArtifact: (taskId: string, artifactId: string) => Promise<void>;
  loadQueueStats: (options?: BridgeCallOptions) => Promise<void>;
  loadSchedules: (options?: BridgeCallOptions) => Promise<void>;
  loadScheduleRunSummaries: (options?: BridgeCallOptions) => Promise<void>;
  previewSchedule: (cronExpression: string, timezone: string) => Promise<string[] | null>;
  createDefaultSchedule: (options?: CreateScheduleOptions) => Promise<boolean>;
  updateScheduleEnabled: (scheduleId: string, enabled: boolean) => Promise<void>;
  updateSchedule: (scheduleId: string, options: CreateScheduleOptions) => Promise<boolean>;
  deleteSchedule: (scheduleId: string) => Promise<void>;
  triggerSchedule: (scheduleId: string) => Promise<void>;
  minimizeWindow: () => Promise<void>;
  toggleMaximizeWindow: () => Promise<void>;
  closeWindow: () => Promise<void>;
};

export type StartRunOptions = {
  browserExecutor?: BrowserExecutorKind;
  concurrency?: number;
  failureStrategy?: RunFailureStrategy;
  flowId?: string;
  mode?: RunMode;
  overrideVariables?: RuntimeVariable[];
  scope?: RunScope;
  screenshot?: boolean;
  startNodeId?: string;
  timeoutMs?: number;
};

export type CreateScheduleOptions = {
  cronExpression?: string;
  enabled?: boolean;
  flowId?: string;
  flowIds?: string[];
  name?: string;
  timezone?: string;
};
